GET http://localhost:3002/api/notes

###
GET http://localhost:3002/api/notes/62eaf7edd17afcbbeb80fde3


###
POST http://localhost:3002/api/notes HTTP/1.1
Content-Type: application/json

{
  "content": "Li",
  "important": true
}

###
PUT http://localhost:3002/api/notes/62eabd98cd1c8a6f0185f99c
Content-Type: application/json

{
  "content": "Linux is awesome",
  "important": true
}

###
DELETE http://localhost:3002/api/notes/62eab1f6303b661884a29475

