GET http://localhost:3002/api/notes

###
GET http://localhost:3002/api/notes/62e8adf8cd725aed936276a3


###
POST http://localhost:3002/api/notes HTTP/1.1
Content-Type: application/json

{
  "content": "Express is awesome",
  "important": true
}

###
PUT http://localhost:3002/api/notes/62ebda4f5c2266bb66d65ae5
Content-Type: application/json

{
  "content": "Express is awesome",
  "important": false
}

###
DELETE http://localhost:3002/api/notes/62ebda4f5c2266bb66d65ae5

