GET http://localhost:3002/api/notes

###
GET http://localhost:3002/api/notes/62e8adf8cd725aed936276a3


###
POST http://localhost:3002/api/notes HTTP/1.1
Content-Type: application/json

{
  "content": "React is awesome",
  "important": true
}

###
PUT http://localhost:3002/api/notes/62eed69baf06e438abb902aa
Content-Type: application/json

{
  "content": "Lodash is awesome",
  "important": false
}

###
DELETE http://localhost:3002/api/notes/62ef2c184525440de8dae482
